AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    CodeUri: packages/lambda/src/functions/

Resources:
  FunctionA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function-a/index.handler
      Runtime: nodejs20.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        EntryPoints:
        - "function-a/index.ts"

  FunctionB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function-b/index.handler
      Runtime: nodejs20.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        EntryPoints:
        - "function-b/index.ts"